on:
  push:
    branches: [master]
  pull_request: {}
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Test
      run: go test ./...
